#!/bin/bash
clear
# Update/Upgrade
echo "$(tput setaf 5)---------------------------------"
echo "Updating and Upgrading the system"
echo "---------------------------------$(tput sgr 0)"
sudo apt update
sudo apt -y upgrade
echo
echo
echo

# Install requirements
echo "$(tput setaf 5)------------------------"
echo 'Installing requirementes'
echo "------------------------$(tput sgr 0)"
sudo apt -y install zsh git vim xcb fonts-powerline tmux zsh-autosuggestions mawk sed htop neovim ncdu snapd default-mysql-client imagemagick
echo
echo
echo

# Install apps
echo "$(tput setaf 5)---------------"
echo 'Installing local apps'
echo "---------------$(tput sgr 0)"
sudo apt -y install  ~/Linux/apps/*.deb
echo
echo
echo

# Install fonts
echo "$(tput setaf 5)----------------"
echo 'Installing fonts'
echo "----------------$(tput sgr 0)"
mkdir ~/.fonts
cp -r ./fonts/* ~/.fonts/
fc-cache -f -v
echo
echo
echo

# ZSH conf
echo "$(tput setaf 5)-----------------"
echo 'ZSH Configuration'
echo "-----------------$(tput sgr 0)"
cp .zshrc ~
sudo mkdir /usr/share/zsh
sudo cp -r ./zsh/* /usr/share/zsh/
echo "$(tput setaf 1)------"
echo " Done "
echo "------$(tput sgr 0)"
echo
echo
echo

# Installing whichSystem
echo "$(tput setaf 5)----------------------"
echo 'Installing whichSystem'
echo "----------------------$(tput sgr 0)"
sudo cp ./apps/whichSystem.py /usr/bin/
sudo chmod +x /usr/bin/whichSystem.py
echo 
echo " whichSystem Installed "
echo
echo

#ZSH as default
echo "$(tput setaf 5)-------------------------------"
echo 'Making ZSH default for everyone'
echo "-------------------------------$(tput sgr 0)"
sudo usermod --shell /usr/bin/zsh $USER
sudo usermod --shell /usr/bin/zsh root

# Solve issues when you migrate from root to a lower privileged user
echo "$(tput setaf 5)-------------------------------------------------------"
echo 'Solving an issue when migrate from root to a lower user'
echo "-------------------------------------------------------$(tput sgr 0)"
sudo setfacl -m u:$USER:rwx
echo "$(tput setaf 1)--------"
echo " Solved "
echo "--------$(tput sgr 0)"

#Powerlevel10k
echo "$(tput setaf 5)---------------"
echo " PowerLevel10k "
echo "---------------$(tput sgr 0)"
sudo git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /usr/bin/powerlevel10k

#Installing SNAP apps
echo "$(tput setaf 5)---------------"
echo " SNAP "
echo "---------------$(tput sgr 0)"
export PATH=/snap/bin:$PATH
sudo snap install searchsploit
sudo snap install mysql-shell

# Install FZF
echo "$(tput setaf 5)-------------"
echo " Install FZF "
echo "-------------$(tput sgr 0)"

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --key-bindings --completion --all 

# Oh My Tmux
echo "$(tput setaf 5)--------------------"
echo " Install Oh-My-Tmux "
echo "--------------------$(tput sgr 0)"
cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .

echo
echo
echo
echo
echo
echo



echo "$(tput setaf 5)--------------------"
echo "Carlos Perez Andrade"
echo "--------------------$(tput sgr 0)"
